spring:
  datasource:
    url: ${DB_URL}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate :
        jdbc :
          lob :
            non_contextual_creation : true
server:
  port: 20000
app :
  version : 1.0.0